config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :customers
root "customers#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :customers
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :company
  belongs_to :post

  validates :family_name,
   presence: true, length: { maximum: 20 }
  validates :given_name,
   presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
   presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
   # validates :sonota,
   #  presence: true, length: { maximum: 20 }

  validates :company_id, presence: true
  validates :post_id, presence: true

  def full_name
    family_name + given_name
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :given_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name, :given_name])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
 before_action :set_customer, only: [:edit, :update, :show, :destroy]

  def index
    @q = Customer.includes(:post, :company).ransack(params[:q])
    @customers = @q.result.page(params[:page])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
   if @customer.save
    redirect_to @customer
   else
    render :new
   end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @customer.destroy
    redirect_to customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id,
      :post_id
    )
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with model: customer, local: true do |form| %>
<% if customer.errors.any? %>
    <div class="alert alert-danger">
      <i class="fa fa-evclamation-triangle"></i>
      <p><b><%= customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :family_name %><br>
    <%= form.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :given_name %><br>
    <%= form.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control" %>
  <div class="form-group">
    <%= form.label :company_id %>
    <%= form.collection_select :company_id, Company.all, :id, :name , { include_blank: "会社を選択してください" },  { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :post_id %>
    <%= form.collection_select :post_id, Post.all, :id, :position_name, { include_blank: "仕事内容を選択してください" }, { class: "form-control" } %>
  </div>


  </div>
  <%= form.submit class: "btn btn-default" %>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>名刺情報の編集</h1>
    <%= render partial: 'form', locals: { customer: @customer } %>
    <button type="button" style="margin-top:20px;" class="btn btn-default" data-toggle="modal" data-target="#delete-customer">
      <i class="fa fa-remove"></i>
      登録情報を削除する</button>
    <%= link_to 'ページを戻る', customer_path(@customer),  style: "margin-top:20px;", class: "btn btn-default" %><i class="fa fa-reply"></i>
  </div>
</div>


<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">名刺情報の削除</h4>
      </div>
      <div class="modal-body">

        <p><i class="fa fa-evclamation-triangle"></i><%= @customer.family_name %>さんの名刺情報を本当に削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">

    <h1 style="text-align: center;"><i class="fa fa-book">
</i>名刺一覧<%= image_tag 'logo.jpg', class: "navbar-brand" %></h1>
  </div>
  <div class="col-lg-6">
    <p  style="text-align: center;">登録済みの名刺情報を表示します</p>
  </div>
  <div class="col-lg-6">
    <%= link_to '新規名刺情報を登録する', new_customer_path, class: "btn btn-default pull-right" %>
  </div>
  <%= search_form_for @q do |f| %>
   <div class="row">
     <div class="col-sm-3 col-xs-12">
       <div class="form-group">
         <%= f.label :family_name_cont, '姓' %>
         <%= f.search_field :family_name_cont, class: "form-control input-sm" %>
       </div>
     </div>
     <div class="col-sm-3 col-xs-12">
       <div class="form-group">
         <%= f.label :given_name_cont, '名' %>
         <%= f.search_field :given_name_cont, class: "form-control input-sm" %>
       </div>
     </div>
     <div class="col-sm-3 col-xs-12">
       <div class="form-group">
         <%= f.label :email_cont, 'メールアドレス' %>
         <%= f.search_field :email_cont, class: "form-control input-sm" %>
       </div>
     </div>
     <div class="col-sm-3 col-xs-12">
       <div class="form-group">
         <%= f.label :company_name_cont, '所属' %>
         <%= f.search_field :company_name_cont, class: "form-control input-sm" %>
       </div>
     </div>
   </div>
   <div class="row">
     <div class="col-xs-12 text-center">
       <%= f.submit "名前、会社を検索", class: "btn btn-default" %>
       <i class="fa fa-search"></i>
       <%= link_to "元に戻す", request.path, class:"btn btn-default" %>
       <i class="fa fa-reply"></i>
     </div>
   </div>
 <% end %>
 <hr />
  <table class="table table-striped">
    <thead>
      <th><%= sort_link(@q, :family_name, "姓") %></th>
      <th><%= sort_link(@q, :given_name, "名") %></th>
      <th><%= sort_link(@q, :email, "メールアドレス") %></th>
      <th><%= sort_link(@q, :company_name, "所属") %></th>
      <th><%= sort_link(@q, :post_position_name, "仕事内容") %></th>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.family_name %></td>
          <td><%= customer.given_name %></td>
          <td><%= customer.email %></td>
          <td><%= customer.company.name %></td>
          <th><%= customer.post.position_name %></th>
          <td><%= link_to '名刺を表示する', customer, class: "btn" %><i class="fa fa-address-card"></i></td>
          <td style="color:red;"><%= link_to '登録情報の編集', customer, class: "btn btn-default btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 <%= paginate @customers %>
</div>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>新規名刺データの入力</h1>
    <%= render partial: 'form', locals: { customer: @customer } %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>名刺情報</h1>
    <dl>
      <dt>氏名</dt>
      <dd style="margin:0px 0px 30px 40px"><%= @customer.full_name %></dd>
      <dt>メールアドレス</dt>
      <dd style="margin:0px 0px 30px 40px"><%= @customer.email %></dd>
      <dt>所属</dt>
      <dd style="margin:0px 0px 30px 40px"><%= @customer.company.name %></dd>
      <dt>仕事内容</dt>
      <dd style="margin:0px 0px 30px 40px"><%= @customer.post.position_name %></dd>
    </dl>
    <%= link_to '登録情報の編集', edit_customer_path(@customer), class: "btn btn-default" %>
    <%= link_to '名刺一覧に戻る', customers_path, class: "btn btn-default" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" style="background-color:deepskyblue;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers" style="color:white;font-size:30px;">Peight</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定", edit_user_registration_path%>  <i class="fa fa-wrench"></i></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>  <i class="fa fa-sign-out"></i></li>
        <% else %>
          <li><%= link_to "新規アカウントを作成する", new_user_registration_path %>  <i class="fa fa-smile-o"></i></li>
          <li><%= link_to "ログイン", new_user_session_path %>  <i class="fa fa-sign-in"></i></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html     style="background-color: beige;>
  <head>
    <title>Seisaku</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">
      <% if notice.present? %>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= notice %></p>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>